[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[dependencies]


[[bin]]
name="01"
path="01/solve.rs"

[[bin]]
name="02"
path="02/solve.rs"

[[bin]]
name="04"
path="04/solve.rs"

[lib]
name="aoc"
path="lib/lib.rs"
